// <auto-generated />
using System;
using LDW.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LDW.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201212234452_AddForum")]
    partial class AddForum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LDW.Domain.Entities.DormitoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Dormitories");
                });

            modelBuilder.Entity("LDW.Domain.Entities.ForumSectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("ForumSectionEntity");
                });

            modelBuilder.Entity("LDW.Domain.Entities.ForumThreadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ForumSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThreadBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreadTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ForumSectionId");

                    b.ToTable("ForumThreadEntity");
                });

            modelBuilder.Entity("LDW.Domain.Entities.ForumThreadReplyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ForumThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParentForumThreadId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentForumThreadReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplyBody")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId1");

                    b.HasIndex("ForumThreadId");

                    b.HasIndex("ParentForumThreadReplyId");

                    b.ToTable("ForumThreadReplyEntity");
                });

            modelBuilder.Entity("LDW.Domain.Entities.UserRefEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("UserRefs");
                });

            modelBuilder.Entity("LDW.Domain.Entities.ForumSectionEntity", b =>
                {
                    b.HasOne("LDW.Domain.Entities.UserRefEntity", "Author")
                        .WithMany("ForumSections")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("LDW.Domain.Entities.ForumThreadEntity", b =>
                {
                    b.HasOne("LDW.Domain.Entities.UserRefEntity", "Author")
                        .WithMany("ForumThreads")
                        .HasForeignKey("AuthorId");

                    b.HasOne("LDW.Domain.Entities.ForumSectionEntity", "ForumSection")
                        .WithMany("ForumThreads")
                        .HasForeignKey("ForumSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LDW.Domain.Entities.ForumThreadReplyEntity", b =>
                {
                    b.HasOne("LDW.Domain.Entities.UserRefEntity", "Author")
                        .WithMany("ForumThreadReplies")
                        .HasForeignKey("AuthorId1");

                    b.HasOne("LDW.Domain.Entities.ForumThreadEntity", "ForumThread")
                        .WithMany("ForumThreadReplies")
                        .HasForeignKey("ForumThreadId");

                    b.HasOne("LDW.Domain.Entities.ForumThreadReplyEntity", "ParentForumThreadReply")
                        .WithMany("ForumThreadReplies")
                        .HasForeignKey("ParentForumThreadReplyId");
                });
#pragma warning restore 612, 618
        }
    }
}
